// This file was generated by Prisma
import "dotenv/config";
import { defineConfig, env } from "prisma/config"; // ✅ Import env dari sini

export default defineConfig({
  schema: "./prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env("DATABASE_URL"), // ✅ Pakai env() function, bukan process.env
  },
});
